version: '3.4'

services:
  variacaopreco.api:
    image: ${DOCKER_REGISTRY-}variacaoprecoapi
    build:
      context: .
      dockerfile: VariacaoPreco.API/Dockerfile

  variacaopreco.data:
    image: ${DOCKER_REGISTRY-}variacaoprecodata
    build:
      context: .
      dockerfile: VariacaoPreco.Data/Dockerfile

  variacaopreco.core:
    image: ${DOCKER_REGISTRY-}variacaoprecocore
    build:
      context: .
      dockerfile: VariacaoPreco.Core/Dockerfile

  variacaopreco.tests:
    image: ${DOCKER_REGISTRY-}variacaoprecotests
    build:
      context: .
      dockerfile: VariacaoPreco.Tests/Dockerfile

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8084:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: 
    driver: local
