version: '3.4'

services:
  variacaopreco.api:
    image: ${DOCKER_REGISTRY-}variacaoprecoapi
    build:
      context: .
      dockerfile: VariacaoPreco.API/Dockerfile

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: 
    driver: local
